CREATE TABLE CONFIGURATION
(
    ID                         BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DATE                       TIMESTAMP,
    USERNAME                   VARCHAR(500),
    N1PIXEL_SIZE               DOUBLE,
    N2BIT_SIZE                 INTEGER,
    N3SAMPLES_PER_PIXEL        INTEGER,
    N4CLOUD_COVERAGE_THRESHOLD DOUBLE,
    N5CLIPPING_THRESHOLD       DOUBLE,
    N7VARIATION_LOW            DOUBLE,
    N7VARIATION_HIGH           DOUBLE,
    N9COLOR_BALANCE_THRESHOLD  DOUBLE,
    N9NOISE_THRESHOLD          DOUBLE
);

INSERT INTO CONFIGURATION (DATE, USERNAME, N1PIXEL_SIZE, N2BIT_SIZE, N3SAMPLES_PER_PIXEL,
                           N4CLOUD_COVERAGE_THRESHOLD,
                           N5CLIPPING_THRESHOLD, N7VARIATION_LOW, N7VARIATION_HIGH, N9COLOR_BALANCE_THRESHOLD,
                           N9NOISE_THRESHOLD)
VALUES (CURRENT_TIMESTAMP, 'metis', 0.5, 8, 4, 2.0, 0.5, 0.1, 0.2, 2.0, 5.0);
