CREATE TABLE REPORT
(
    ID              BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DATE            TIMESTAMP,
    FILES_LOCATION  VARCHAR(500),
    PATH            VARCHAR(500),
    REPORT_LOCATION VARCHAR(500)
);
