server:
  ssl:
    #key-store: classpath:metis.p12
    key-store: file:metis.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: metis
    key-password: password
  port: 443
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,text/plain

spring:
  jmx:
    enabled: false
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: rabbituser
  #    password: 6561YM4COS
  application:
    name: Metis
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    enabled: true
    #prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
    suffix: .html
  web:
    resources:
      cache:
        period: 0
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
  datasource:
    url: jdbc:h2:file:./metis.db;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389
logging:
  level:
    com.amaxilatis.metis: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO

metis:
  reportLocation: reports
  resultsLocation: results
  thumbnailLocation: thumb
  histogramLocation: hist
  #filesLocation: files
  filesLocation: "O:\\"
  version: ^project.version^
  processing:
    threads: -1

