spring:
  jmx:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbituser
    password: 6561YM4COS
  application:
    name: Metis
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    enabled: true
    #    prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
    suffix: .html
  web:
    resources:
      cache:
        period: 0

logging:
  level:
    com.amaxilatis.metis: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO

metis:
  reportLocation: reports
  resultsLocation: results
  filesLocation: "S:\\OPEKEPE\\"
  version: 0.3.1-SNAPSHOT
  processing:
    threads: -1

