spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: Metis
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    enabled: true
    #prefix: classpath:/templates/
    prefix: file:src/main/resources/templates/
    suffix: .html
  web:
    resources:
      cache:
        period: 0

logging:
  level:
    com.amaxilatis.metis: DEBUG
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO
metis.reportLocation: reports
metis.filesLocation: "S:\\OPEKEPE\\"
metis.version: 0.3.0-SNAPSHOT

