spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}
  thymeleaf:
    cache: true
    prefix: classpath:/templates/

logging:
  level:
    org.springframework.messaging: ERROR
    org.springframework.web.socket: ERROR

metis:
  reportLocation: ${METIS_REPORTS_DIR:/home/metis/reports}
  filesLocation: ${METIS_FILES_DIR:/home/metis/images}
  processing:
    threads: ${METIS_THREADS:-1}

