server:
  ssl:
    key-store: file:metis.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: metis
    key-password: password
  port: 443
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,text/plain

spring:
  jmx:
    enabled: false
  application:
    name: Metis
  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      cache:
        period: 0
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
  datasource:
    url: jdbc:h2:file:./metis.db;MODE=Oracle;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
logging:
  level:
    com.amaxilatis.metis: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO

metis:
  reportLocation: reports
  resultsLocation: results
  thumbnailLocation: thumb
  histogramLocation: hist
  cloudMaskLocation: cloud
  filesLocation: files
  version: ^project.version^
  processing:
    threads: -1
  ldap:
    domain: localhost
    url: ldap://localhost
    use: true

