server:
  servlet:
    session:
      timeout: 8h
  ssl:
    key-store: file:metis.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: metis
    key-password: password
  port: 443
  http2:
    enabled: false
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,text/plain

spring:
  jmx:
    enabled: false
  application:
    name: Metis
  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      cache:
        period: 0
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
  datasource:
    url: jdbc:derby:directory:metisdb
    username: sa
    password: password
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
logging:
  level:
    com.amaxilatis.metis: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO

metis:
  reportLocation: reports
  resultsLocation: results
  thumbnailLocation: thumb
  histogramLocation: hist
  cloudMaskLocation: cloud
  filesLocation: files
  storeHelperMasks: true
  version: ^project.version^
  dbBackupLocation: backup
  uncompressedLocation: unc
  processing:
    threads: -1
  ldap:
    domain: localhost
    url: ldap://localhost
    use: true
  notificationEmail: notification@notification.com
  domain: https://localhost

spring.mail:
  host: smtp.host
  port: 587
  username: username
  password: password
  properties.mail.smtp:
    auth: true
    starttls.enable: true
